"""
Combine supplementary figure panels into the final composite images used by the
paper reproducibility package.

Reads panel PNGs from ``Supplementary Materials/figures/FigS*/`` and writes the
combined outputs back to ``Supplementary Materials/figures/``.
"""

from pathlib import Path
from PIL import Image
import math

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
SM_FIGS = PROJECT_ROOT / 'Supplementary Materials' / 'figures'


def combine_panels(panel_paths: list, output_name: str, ncols: int = 2,
                   target_width: int = 3000):
    """Combine panel images into a grid."""
    panels = []
    for p in panel_paths:
        if p.exists():
            panels.append(Image.open(p))
        else:
            print(f"  ⚠️ Missing: {p.name}")

    if not panels:
        print(f"  ❌ No panels found for {output_name}")
        return

    nrows = math.ceil(len(panels) / ncols)
    pw = target_width // ncols
    resized = []
    for img in panels:
        ratio = pw / img.width
        resized.append(img.resize((pw, int(img.height * ratio)), Image.LANCZOS))

    max_h = max(r.height for r in resized)
    canvas = Image.new('RGB', (pw * ncols, max_h * nrows), (255, 255, 255))

    for i, img in enumerate(resized):
        col, row = i % ncols, i // ncols
        canvas.paste(img, (col * pw, row * max_h))

    out_path = SM_FIGS / f'{output_name}.png'
    canvas.save(out_path, dpi=(300, 300))
    print(f"  ✅ {out_path}")

    for img in panels:
        img.close()


def main():
    print("=" * 60)
    print("Combining supplementary figure panels")
    print("=" * 60)

    # Fig S1: single image, just copy
    s1 = SM_FIGS / 'FigS1' / 'FigS1_IVS_cultural_map.png'
    if s1.exists():
        img = Image.open(s1)
        img.save(SM_FIGS / 'FigS1_IVS_cultural_map.png', dpi=(300, 300))
        img.close()
        print("Fig S1: ✅ copied")

    # Fig S2: unified combined figure generated by generate_figS2_model_imitation.py
    print("\nFig S2 (Model Imitation): unified combined figure")
    s2_combined = SM_FIGS / 'FigS2' / 'FigS2_combined.png'
    if s2_combined.exists():
        img = Image.open(s2_combined)
        img.save(SM_FIGS / 'FigS2_model_imitation.png', dpi=(300, 300))
        img.close()
        print("  ✅ Copied unified FigS2")
    else:
        print("  ⚠️ FigS2_combined.png not found – run generate_figS2_model_imitation.py first")

    # Fig S3: unified combined figure generated by generate_figS3_orientalism.py
    print("\nFig S3 (Orientalism): unified combined figure")
    s3_combined = SM_FIGS / 'FigS3' / 'FigS3_orientalism_combined.png'
    if s3_combined.exists():
        img = Image.open(s3_combined)
        img.save(SM_FIGS / 'FigS3_orientalism.png', dpi=(300, 300))
        img.close()
        print("  ✅ Copied unified FigS3")
    else:
        print("  ⚠️ FigS3_orientalism_combined.png not found – run generate_figS3_orientalism.py first")

    # Fig S4: 3 panels (1×3) - trajectory, distance, gradient
    print("\nFig S4 (East Asia): 3 panels")
    combine_panels([
        SM_FIGS / 'FigS4' / 'FigS4A_east_asia_trajectory.png',
        SM_FIGS / 'FigS4' / 'FigS4B_east_asia_distance_comparison.png',
        SM_FIGS / 'FigS4' / 'FigS4C_east_asia_english_gradient.png',
    ], 'FigS4_east_asia', ncols=3)

    print("\n" + "=" * 60)
    print("Done! Combined figures saved to:")
    print(f"  {SM_FIGS}")
    print("=" * 60)


if __name__ == '__main__':
    main()
